version: '3'
services:
  api:
    container_name: info-sistemas-api
    build:
      context: ./api/
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 3000
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: info
      MYSQL_DATABASE: info_sistemas
      MYSQL_PASSWORD: sistemas
      DATABASE_URL: mysql://info:sistemas@db:3306/info_sistemas
    ports:
      - 3000:3000
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - my-network
  app:
    build:
      dockerfile: Dockerfile
      context: ./app
    ports:
      - 8081:80
    links:
      - api
  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: info
      MYSQL_DATABASE: info_sistemas
      MYSQL_PASSWORD: sistemas
    networks:
      - my-network

networks:
  my-network: