version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - db
    networks:
      - my-network
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./app:/usr/src/app
    networks:
      - my-network
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: infosistemas
      MYSQL_USER: info
      MYSQL_PASSWORD: sistemas
    networks:
      - my-network

networks:
  my-network:
